# - name: Install nginx 
#   ansible.builtin.apt:
#     name: nginx
#     state: present

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - net-tools
    - vim
    - nginx


- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Template a file to /etc/nginx/conf.d/
  ansible.builtin.template:
    src: myconf.conf.j2
    dest: /etc/nginx/conf.d/
    owner: www-data
    group: www-data
    mode: '0644'   
  notify:
    - Restart Nginx