version: '3.9'

services:

  nginx:
      image: nginx:latest
      ports:
        - 80:80
      volumes:
        - ./nginx:/etc/nginx/conf.d
      restart: always
      networks:
      - wpi_net

  nodejs:
      image: testnode:v1
      ports:
        - 8080:8080
      restart: always
      networks:
        - wpi_net 

networks:
  wpi_net:
    driver: bridge
 
